### ISSUE TITLE
[Bug] Installation der PHP Versionen

### ISSUE THREAD

**Issue by Bubbelwubbel** [MinehubDE/linux-beginner-scripts#10]
Liebe Damen und Herren dieser Welt,

ich bin Bubbelwubbel und möchte sie Rechtherzlich in diesem Issues einladen!

Mein Bug ist, wenn man nen Bedrock Server erstellt, bzw. PocketMine, geht der Server nicht. Ich schätze es liegt an der PHP Version. Pls fixen. Wenn sie dies nicht wissen, wäre ich auch bereits ihnen dabei zuhelfen! <3

Euer @FlxiBoy1313

**Comment by MinehubDE** [comment]
fixed by https://github.com/MinehubDE/linux-beginner-scripts/commit/1468ef080df1c7e485d4dcd023f021de9716e6bc
