### ISSUE TITLE
Installation fehler

### ISSUE THREAD

**Issue by DarkRoseCode** [MinehubDE/linux-beginner-scripts#5]
Ich habe Mich eingeloggt und wollte für mich und paar freunde ein normalen Java Server erstellen Dann tauchte da was auf von wegen Instillation Und ich musste mit YES antworten Dann kam der fehler code:   

Please insert 'YES' to allow the installation. Otherwise this script will exit here: YES
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.de.debian.org/debian stretch InRelease
Hit:3 http://ftp.de.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.de.debian.org/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package default-jre-headless is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'default-jre-headless' has no installation candidate

---------------------------------------------------------------------------------

Installation failed, trying to fix...

---------------------------------------------------------------------------------

Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  fontconfig-config fonts-dejavu-core java-common libavahi-client3
  libavahi-common-data libavahi-common3 libcups2 libdbus-1-3 libfontconfig1
  libjpeg62-turbo liblcms2-2 libnspr4 libnss3 libpcsclite1 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxi6 libxrender1 libxtst6
  openjdk-8-jre-headless x11-common
Use 'apt autoremove' to remove them.
E: Can't find a source to download version '8u252-b09-1~deb9u1' of 'openjdk-8-jre-headless:amd64'
Could not install dependencies. Will exit now.

nutze Debian 9

**Comment by MinehubDE** [comment]
Auf einer frischen Installation von Debian 9 passiert das nicht. Deine Sources oder dein Apt-Cache scheinen das Problem zu sein.
Versuche es erneut, nachdem du zuvor folgendes eingegeben hast:

`apt-get -y autoremove`
`apt-get clean`
