### ISSUE TITLE
[Idee] Zu dem Scripts

### ISSUE THREAD

**Issue by Bubbelwubbel** [MinehubDE/linux-beginner-scripts#7]
Guten Morgen/Mittag/Abend,

ich möchte eine Idee zum Script bringen.

Die Idee ist folgendes, ein Backup Befehl wo der home Ordner zur .zip gemacht wird und im root Ordner gelagert wird. Der Befehl dafür könnte z.B das sein: **cd linux-beginner-scripts && ./create-backup.sh**.

Mit Freundlich Grüßen
Felix

**Comment by 0-unkn0wn-0** [comment]
Finde die Idee ansich nicht schlecht. Aber würde mir wünschen das man die Ordner selbst aussuchen kann die man backupen kann

**Comment by Elament542YT** [comment]
Ich finde die Idee gut.

**Comment by Cownex** [comment]
Könnte gut sein

**Comment by Conplayers22** [comment]
Die Idee ist gut wäre cool wenn sie umgesetzt werden könnte.
